
# Project information
site_name: SyncStage Docs
site_url: https://docs.sync-stage.com
site_author: Patryk Kaczmarek, Mateusz Mul
site_description: >-
  SyncStage is a patent pending infrastructure platform that allows any application developer to create a synchronous audio experience within their application.

# Copyright
copyright: Copyright &copy; 2023 Open Sesame Media, Inc.

# Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png

  font:
    text: Josefin Sans
    code: Source Code Pro 
    
  features:
    - header.autohide    
    - content.tooltips
  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode        
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

# Customization
extra:
  latest_android_sdk_version: v0.6.0
  latest_ios_sdk_version: v0.5.1
  latest_web_sdk_version: v0.4.0
  latest_desktop_agent_for_macos_url: https://public.sync-stage.com/agent/macos/prod/0.3.0/SyncStageAgent_0.3.0.dmg
  latest_desktop_agent_for_windows_url: https://public.sync-stage.com/agent/win/prod/0.1.0/SyncStageAgent_0.1.0.exe

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
    actions:
      - accept
      - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opensesamemedia
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opensesamemedia
  analytics:
    provider: google
    property: G-7YFZKQNWH4

    

extra_css:
  - stylesheets/extra.css
  - stylesheets/css-v1.0.2.css
  - stylesheets/neoteroi-mkdocs.min.css


# Page tree
nav:
  # - SyncStage:
  - What is SyncStage?: index.md
  - Architecture & Glossary: architecture-and-glossary.md
  - SyncStage SDK for Android:
    - Overview: android/overview.md
    - Quickstart: android/quickstart.md
    - Reference:
      - Methods: android/sdk-methods.md
      - Delegates: android/sdk-delegates.md
      - Error codes: android/sdk-error-codes.md
      - Previous versions:
        - 0.5.2:
          - Methods: android/versions/0.5.2/sdk-methods.md
          - Delegates: android/versions/0.5.2/sdk-delegates.md
          - Error codes: android/versions/0.5.2/sdk-error-codes.md   
        - 0.5.1:
          - Methods: android/versions/0.5.1/sdk-methods.md
          - Delegates: android/versions/0.5.1/sdk-delegates.md
          - Error codes: android/versions/0.5.1/sdk-error-codes.md   
        - 0.5.0:
          - Methods: android/versions/0.5.0/sdk-methods.md
          - Delegates: android/versions/0.5.0/sdk-delegates.md
          - Error codes: android/versions/0.5.0/sdk-error-codes.md   
        - 0.4.1:
          - Methods: android/versions/0.4.1/sdk-methods.md
          - Delegates: android/versions/0.4.1/sdk-delegates.md
          - Error codes: android/versions/0.4.1/sdk-error-codes.md      
        - 0.4.0:
          - Methods: android/versions/0.4.0/sdk-methods.md
          - Delegates: android/versions/0.4.0/sdk-delegates.md
          - Error codes: android/versions/0.4.0/sdk-error-codes.md 
    - Test App: android/test-app.md
    - Changelog: android/changelog.md
    - Known issues: android/known-issues.md  
  - SyncStage SDK for iOS:
    - Overview: ios/overview.md
    - Quickstart: ios/quickstart.md
    - Reference:
      - Methods: ios/sdk-methods.md
      - Delegates: ios/sdk-delegates.md
      - Error codes: ios/sdk-error-codes.md      
      - Previous versions:
        - 0.5.0:
          - Methods: ios/versions/0.5.0/sdk-methods.md
          - Delegates: ios/versions/0.5.0/sdk-delegates.md
          - Error codes: ios/versions/0.5.0/sdk-error-codes.md      
        - 0.4.0:
          - Methods: ios/versions/0.4.0/sdk-methods.md
          - Delegates: ios/versions/0.4.0/sdk-delegates.md
          - Error codes: ios/versions/0.4.0/sdk-error-codes.md        
        - 0.3.1:
          - Methods: ios/versions/0.3.1/sdk-methods.md
          - Delegates: ios/versions/0.3.1/sdk-delegates.md
          - Error codes: ios/versions/0.3.1/sdk-error-codes.md        
    - Test App: ios/test-app.md      
    - Changelog: ios/changelog.md  
  - SyncStage SDK for Web:
    - Overview: web/overview.md
    - Quickstart: web/quickstart.md
    - Provisioning: web/provisioning.md
    - Desktop Agent:
      - macOS: web/desktop-agent-macos.md
      - Windows: web/desktop-agent-windows.md
    - Reference:
      - Methods: web/sdk-methods.md
      - Delegates: web/sdk-delegates.md
      - Error codes: web/sdk-error-codes.md   
      - Previous versions:
        - 0.3.0:
          - Methods: web/versions/0.3.0/sdk-methods.md
          - Delegates: web/versions/0.3.0/sdk-delegates.md
          - Error codes: web/versions/0.3.0/sdk-error-codes.md  
        - 0.2.0:
          - Methods: web/versions/0.2.0/sdk-methods.md
          - Delegates: web/versions/0.2.0/sdk-delegates.md
          - Error codes: web/versions/0.2.0/sdk-error-codes.md  
        - 0.1.0:
          - Methods: web/versions/0.1.0/sdk-methods.md
          - Delegates: web/versions/0.1.0/sdk-delegates.md
          - Error codes: web/versions/0.1.0/sdk-error-codes.md  
    - Test App: web/test-app.md
    - Changelog: web/changelog.md
    - Known issues: web/known-issues.md    
  - Getting ultra low latency experience: low-latency-experience.md
  - Developer API: developer-api/swagger.md
  - Recommendations: recommendations.md
  - Help:
    - FAQ: help/faq.md
    - Reporting a bug: help/report-a-bug.md
    - Reporting an issue in docs: help/report-an-issue-in-docs.md
    - Asking a question: help/ask-a-question.md
  # - Roadmap: roadmap.md    
  - Acknowledgements: acknowledgements.md


# Extensions
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition      
  - abbr
  - attr_list # Needed for opening links in a new tab.
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - neoteroi.timeline

plugins:
  - search
  - glightbox
  - mkdocs-video
  - tags
  - macros
  - swagger-ui-tag
